"""create_backtest_runs_and_trades

Revision ID: 208463870910
Revises: f3a4b5c6d7e8
Create Date: 2026-06-24 09:41:27.115029

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '208463870910'
down_revision: str | Sequence[str] | None = 'f3a4b5c6d7e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('data_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_cost_bps', sa.BigInteger(), nullable=False),
    sa.Column('slippage_bps', sa.BigInteger(), nullable=False),
    sa.Column('risk_free_rate_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('parameters_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('annualized_return_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volatility_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('win_rate_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('exposure_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('equity_curve_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_asset_id'), 'backtest_runs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('executed_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('executed_exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reason_entry', sa.String(length=50), nullable=False),
    sa.Column('reason_exit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.drop_index(op.f('ix_price_bars_asset_timeframe_ts'), table_name='price_bars')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_price_bars_asset_timeframe_ts'), 'price_bars', ['asset_id', 'timeframe', sa.literal_column('timestamp DESC')], unique=False)  # noqa: E501
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_asset_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
